---

- name: Java and Tomcat Installation and configuration
  hosts: web-server
  sudo: True
  tasks:
    - name: Installing Required items.
      apt: pkg={{ item }} state=latest
      with_items:
        - curl
        - wget

  roles:
    - role: java

    - role: tomcat
         
